# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=2048m -Dfile.encoding=UTF-8
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
org.gradle.parallel=false
# When enabled, the Configuration Cache allows Gradle to skip the configuration
# phase entirely if nothing that affects the build configuration (such as build scripts)
# has changed. Additionally, Gradle applies performance optimizations to task execution.
org.gradle.configuration-cache=false
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Memory settings for Android worker processes
android.memorySettings.workerProcess.maxHeapSize=4g
android.enableDexingArtifactTransform.parallel=false

# 解决多个 Android 环境变量冲突导致的编译失败 (AGP 8.3+)
android.overridePathCheck=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE

